version: "2"

linters:
  default: standard

  enable:
    - misspell
    - revive
    - unparam
    - gosec
    - gocritic
    - goconst
    - testifylint


  exclusions:
    rules:
      - path: ^example/
        linters:
          - revive