// Code generated by protoc-gen-go-guard. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/corner_cases/default_and_empty.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-guard/pkg/guard"
)

var guardService_EmptyServiceRules = guard.Service{
	Name: "EmptyServiceRules",
	Rules: []*guard.Rule{
		{},
	},
	Methods: map[string]*guard.Method{},
}

func (UnimplementedEmptyServiceRulesServer) GetGuardService() *guard.Service {
	return &guardService_EmptyServiceRules
}

var guardService_EmptyMethodRules = guard.Service{
	Name: "EmptyMethodRules",
	Methods: map[string]*guard.Method{
		"GetOne": {
			Rules: []*guard.Rule{
				{},
			},
		},
	},
}

func (UnimplementedEmptyMethodRulesServer) GetGuardService() *guard.Service {
	return &guardService_EmptyMethodRules
}

var guardService_EmptyServiceAndMethodRules = guard.Service{
	Name: "EmptyServiceAndMethodRules",
	Rules: []*guard.Rule{
		{},
	},
	Methods: map[string]*guard.Method{
		"GetOne": {
			Rules: []*guard.Rule{
				{},
			},
		},
	},
}

func (UnimplementedEmptyServiceAndMethodRulesServer) GetGuardService() *guard.Service {
	return &guardService_EmptyServiceAndMethodRules
}
