// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: example/api/corner_cases/default_and_empty.proto

package corner_cases

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DefaultRulesClient is the client API for DefaultRules service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DefaultRulesClient interface {
	// Call with default rules.
	GetOne(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type defaultRulesClient struct {
	cc grpc.ClientConnInterface
}

func NewDefaultRulesClient(cc grpc.ClientConnInterface) DefaultRulesClient {
	return &defaultRulesClient{cc}
}

func (c *defaultRulesClient) GetOne(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.corner_cases.DefaultRules/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DefaultRulesServer is the server API for DefaultRules service.
// All implementations must embed UnimplementedDefaultRulesServer
// for forward compatibility
type DefaultRulesServer interface {
	// Call with default rules.
	GetOne(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedDefaultRulesServer()
}

// UnimplementedDefaultRulesServer must be embedded to have forward compatible implementations.
type UnimplementedDefaultRulesServer struct {
}

func (UnimplementedDefaultRulesServer) GetOne(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedDefaultRulesServer) mustEmbedUnimplementedDefaultRulesServer() {}

// UnsafeDefaultRulesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DefaultRulesServer will
// result in compilation errors.
type UnsafeDefaultRulesServer interface {
	mustEmbedUnimplementedDefaultRulesServer()
}

func RegisterDefaultRulesServer(s grpc.ServiceRegistrar, srv DefaultRulesServer) {
	s.RegisterService(&DefaultRules_ServiceDesc, srv)
}

func _DefaultRules_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultRulesServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.corner_cases.DefaultRules/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultRulesServer).GetOne(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DefaultRules_ServiceDesc is the grpc.ServiceDesc for DefaultRules service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DefaultRules_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.corner_cases.DefaultRules",
	HandlerType: (*DefaultRulesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _DefaultRules_GetOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/api/corner_cases/default_and_empty.proto",
}

// EmptyServiceRulesClient is the client API for EmptyServiceRules service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmptyServiceRulesClient interface {
	// Call with inherited rules.
	GetOne(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type emptyServiceRulesClient struct {
	cc grpc.ClientConnInterface
}

func NewEmptyServiceRulesClient(cc grpc.ClientConnInterface) EmptyServiceRulesClient {
	return &emptyServiceRulesClient{cc}
}

func (c *emptyServiceRulesClient) GetOne(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.corner_cases.EmptyServiceRules/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmptyServiceRulesServer is the server API for EmptyServiceRules service.
// All implementations must embed UnimplementedEmptyServiceRulesServer
// for forward compatibility
type EmptyServiceRulesServer interface {
	// Call with inherited rules.
	GetOne(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedEmptyServiceRulesServer()
}

// UnimplementedEmptyServiceRulesServer must be embedded to have forward compatible implementations.
type UnimplementedEmptyServiceRulesServer struct {
}

func (UnimplementedEmptyServiceRulesServer) GetOne(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedEmptyServiceRulesServer) mustEmbedUnimplementedEmptyServiceRulesServer() {}

// UnsafeEmptyServiceRulesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmptyServiceRulesServer will
// result in compilation errors.
type UnsafeEmptyServiceRulesServer interface {
	mustEmbedUnimplementedEmptyServiceRulesServer()
}

func RegisterEmptyServiceRulesServer(s grpc.ServiceRegistrar, srv EmptyServiceRulesServer) {
	s.RegisterService(&EmptyServiceRules_ServiceDesc, srv)
}

func _EmptyServiceRules_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmptyServiceRulesServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.corner_cases.EmptyServiceRules/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmptyServiceRulesServer).GetOne(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// EmptyServiceRules_ServiceDesc is the grpc.ServiceDesc for EmptyServiceRules service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmptyServiceRules_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.corner_cases.EmptyServiceRules",
	HandlerType: (*EmptyServiceRulesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _EmptyServiceRules_GetOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/api/corner_cases/default_and_empty.proto",
}

// EmptyMethodRulesClient is the client API for EmptyMethodRules service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmptyMethodRulesClient interface {
	// Call with empty rules.
	GetOne(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type emptyMethodRulesClient struct {
	cc grpc.ClientConnInterface
}

func NewEmptyMethodRulesClient(cc grpc.ClientConnInterface) EmptyMethodRulesClient {
	return &emptyMethodRulesClient{cc}
}

func (c *emptyMethodRulesClient) GetOne(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.corner_cases.EmptyMethodRules/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmptyMethodRulesServer is the server API for EmptyMethodRules service.
// All implementations must embed UnimplementedEmptyMethodRulesServer
// for forward compatibility
type EmptyMethodRulesServer interface {
	// Call with empty rules.
	GetOne(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedEmptyMethodRulesServer()
}

// UnimplementedEmptyMethodRulesServer must be embedded to have forward compatible implementations.
type UnimplementedEmptyMethodRulesServer struct {
}

func (UnimplementedEmptyMethodRulesServer) GetOne(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedEmptyMethodRulesServer) mustEmbedUnimplementedEmptyMethodRulesServer() {}

// UnsafeEmptyMethodRulesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmptyMethodRulesServer will
// result in compilation errors.
type UnsafeEmptyMethodRulesServer interface {
	mustEmbedUnimplementedEmptyMethodRulesServer()
}

func RegisterEmptyMethodRulesServer(s grpc.ServiceRegistrar, srv EmptyMethodRulesServer) {
	s.RegisterService(&EmptyMethodRules_ServiceDesc, srv)
}

func _EmptyMethodRules_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmptyMethodRulesServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.corner_cases.EmptyMethodRules/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmptyMethodRulesServer).GetOne(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// EmptyMethodRules_ServiceDesc is the grpc.ServiceDesc for EmptyMethodRules service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmptyMethodRules_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.corner_cases.EmptyMethodRules",
	HandlerType: (*EmptyMethodRulesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _EmptyMethodRules_GetOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/api/corner_cases/default_and_empty.proto",
}

// EmptyServiceAndMethodRulesClient is the client API for EmptyServiceAndMethodRules service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmptyServiceAndMethodRulesClient interface {
	// Call with empty rules.
	GetOne(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type emptyServiceAndMethodRulesClient struct {
	cc grpc.ClientConnInterface
}

func NewEmptyServiceAndMethodRulesClient(cc grpc.ClientConnInterface) EmptyServiceAndMethodRulesClient {
	return &emptyServiceAndMethodRulesClient{cc}
}

func (c *emptyServiceAndMethodRulesClient) GetOne(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.corner_cases.EmptyServiceAndMethodRules/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmptyServiceAndMethodRulesServer is the server API for EmptyServiceAndMethodRules service.
// All implementations must embed UnimplementedEmptyServiceAndMethodRulesServer
// for forward compatibility
type EmptyServiceAndMethodRulesServer interface {
	// Call with empty rules.
	GetOne(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedEmptyServiceAndMethodRulesServer()
}

// UnimplementedEmptyServiceAndMethodRulesServer must be embedded to have forward compatible implementations.
type UnimplementedEmptyServiceAndMethodRulesServer struct {
}

func (UnimplementedEmptyServiceAndMethodRulesServer) GetOne(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedEmptyServiceAndMethodRulesServer) mustEmbedUnimplementedEmptyServiceAndMethodRulesServer() {
}

// UnsafeEmptyServiceAndMethodRulesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmptyServiceAndMethodRulesServer will
// result in compilation errors.
type UnsafeEmptyServiceAndMethodRulesServer interface {
	mustEmbedUnimplementedEmptyServiceAndMethodRulesServer()
}

func RegisterEmptyServiceAndMethodRulesServer(s grpc.ServiceRegistrar, srv EmptyServiceAndMethodRulesServer) {
	s.RegisterService(&EmptyServiceAndMethodRules_ServiceDesc, srv)
}

func _EmptyServiceAndMethodRules_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmptyServiceAndMethodRulesServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.corner_cases.EmptyServiceAndMethodRules/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmptyServiceAndMethodRulesServer).GetOne(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// EmptyServiceAndMethodRules_ServiceDesc is the grpc.ServiceDesc for EmptyServiceAndMethodRules service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmptyServiceAndMethodRules_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.corner_cases.EmptyServiceAndMethodRules",
	HandlerType: (*EmptyServiceAndMethodRulesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _EmptyServiceAndMethodRules_GetOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/api/corner_cases/default_and_empty.proto",
}
