// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/corner_cases/default_and_empty.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
)

var rbacService_EmptyServiceRules = rbac.Service{
	Name:    "EmptyServiceRules",
	Rules:   &rbac.Rules{},
	Methods: map[string]*rbac.Method{},
}

func (UnimplementedEmptyServiceRulesServer) GetRBACService() *rbac.Service {
	return &rbacService_EmptyServiceRules
}

var rbacService_EmptyMethodRules = rbac.Service{
	Name: "EmptyMethodRules",
	Methods: map[string]*rbac.Method{
		"GetOne": {
			Rules: &rbac.Rules{},
		},
	},
}

func (UnimplementedEmptyMethodRulesServer) GetRBACService() *rbac.Service {
	return &rbacService_EmptyMethodRules
}

var rbacService_EmptyServiceAndMethodRules = rbac.Service{
	Name:  "EmptyServiceAndMethodRules",
	Rules: &rbac.Rules{},
	Methods: map[string]*rbac.Method{
		"GetOne": {
			Rules: &rbac.Rules{},
		},
	},
}

func (UnimplementedEmptyServiceAndMethodRulesServer) GetRBACService() *rbac.Service {
	return &rbacService_EmptyServiceAndMethodRules
}
