// Code generated by protoc-gen-go-guard. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/corner_cases/inherit_and_override.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-guard/pkg/guard"
)

var guardService_InheritAndOverrideOne = guard.Service{
	Name: "InheritAndOverrideOne",
	Methods: map[string]*guard.Method{
		"OverriddenMethod": {
			Rules: []*guard.Rule{
				{
					AllowPublic: guard.Ptr(true),
				},
			},
		},
	},
}

func (UnimplementedInheritAndOverrideOneServer) GetGuardService() *guard.Service {
	return &guardService_InheritAndOverrideOne
}

var guardService_InheritAndOverrideTwo = guard.Service{
	Name: "InheritAndOverrideTwo",
	Rules: []*guard.Rule{
		{
			AllowPublic: guard.Ptr(true),
		},
	},
	Methods: map[string]*guard.Method{
		"OverriddenMethod": {
			Rules: []*guard.Rule{
				{
					AllowPublic: guard.Ptr(false),
				},
			},
		},
	},
}

func (UnimplementedInheritAndOverrideTwoServer) GetGuardService() *guard.Service {
	return &guardService_InheritAndOverrideTwo
}
