// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: example/api/corner_cases/inherit_and_override.proto

package corner_cases

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InheritAndOverrideOneClient is the client API for InheritAndOverrideOne service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InheritAndOverrideOneClient interface {
	// Call default rules.
	InheritedMethod(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Call override default rules.
	OverriddenMethod(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type inheritAndOverrideOneClient struct {
	cc grpc.ClientConnInterface
}

func NewInheritAndOverrideOneClient(cc grpc.ClientConnInterface) InheritAndOverrideOneClient {
	return &inheritAndOverrideOneClient{cc}
}

func (c *inheritAndOverrideOneClient) InheritedMethod(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.corner_cases.InheritAndOverrideOne/InheritedMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inheritAndOverrideOneClient) OverriddenMethod(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.corner_cases.InheritAndOverrideOne/OverriddenMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InheritAndOverrideOneServer is the server API for InheritAndOverrideOne service.
// All implementations must embed UnimplementedInheritAndOverrideOneServer
// for forward compatibility
type InheritAndOverrideOneServer interface {
	// Call default rules.
	InheritedMethod(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Call override default rules.
	OverriddenMethod(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedInheritAndOverrideOneServer()
}

// UnimplementedInheritAndOverrideOneServer must be embedded to have forward compatible implementations.
type UnimplementedInheritAndOverrideOneServer struct {
}

func (UnimplementedInheritAndOverrideOneServer) InheritedMethod(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InheritedMethod not implemented")
}
func (UnimplementedInheritAndOverrideOneServer) OverriddenMethod(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OverriddenMethod not implemented")
}
func (UnimplementedInheritAndOverrideOneServer) mustEmbedUnimplementedInheritAndOverrideOneServer() {}

// UnsafeInheritAndOverrideOneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InheritAndOverrideOneServer will
// result in compilation errors.
type UnsafeInheritAndOverrideOneServer interface {
	mustEmbedUnimplementedInheritAndOverrideOneServer()
}

func RegisterInheritAndOverrideOneServer(s grpc.ServiceRegistrar, srv InheritAndOverrideOneServer) {
	s.RegisterService(&InheritAndOverrideOne_ServiceDesc, srv)
}

func _InheritAndOverrideOne_InheritedMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InheritAndOverrideOneServer).InheritedMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.corner_cases.InheritAndOverrideOne/InheritedMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InheritAndOverrideOneServer).InheritedMethod(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InheritAndOverrideOne_OverriddenMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InheritAndOverrideOneServer).OverriddenMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.corner_cases.InheritAndOverrideOne/OverriddenMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InheritAndOverrideOneServer).OverriddenMethod(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// InheritAndOverrideOne_ServiceDesc is the grpc.ServiceDesc for InheritAndOverrideOne service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InheritAndOverrideOne_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.corner_cases.InheritAndOverrideOne",
	HandlerType: (*InheritAndOverrideOneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InheritedMethod",
			Handler:    _InheritAndOverrideOne_InheritedMethod_Handler,
		},
		{
			MethodName: "OverriddenMethod",
			Handler:    _InheritAndOverrideOne_OverriddenMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/api/corner_cases/inherit_and_override.proto",
}

// InheritAndOverrideTwoClient is the client API for InheritAndOverrideTwo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InheritAndOverrideTwoClient interface {
	// Call with inherited rules.
	InheritedMethod(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Call with override rules.
	OverriddenMethod(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type inheritAndOverrideTwoClient struct {
	cc grpc.ClientConnInterface
}

func NewInheritAndOverrideTwoClient(cc grpc.ClientConnInterface) InheritAndOverrideTwoClient {
	return &inheritAndOverrideTwoClient{cc}
}

func (c *inheritAndOverrideTwoClient) InheritedMethod(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.corner_cases.InheritAndOverrideTwo/InheritedMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inheritAndOverrideTwoClient) OverriddenMethod(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.corner_cases.InheritAndOverrideTwo/OverriddenMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InheritAndOverrideTwoServer is the server API for InheritAndOverrideTwo service.
// All implementations must embed UnimplementedInheritAndOverrideTwoServer
// for forward compatibility
type InheritAndOverrideTwoServer interface {
	// Call with inherited rules.
	InheritedMethod(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Call with override rules.
	OverriddenMethod(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedInheritAndOverrideTwoServer()
}

// UnimplementedInheritAndOverrideTwoServer must be embedded to have forward compatible implementations.
type UnimplementedInheritAndOverrideTwoServer struct {
}

func (UnimplementedInheritAndOverrideTwoServer) InheritedMethod(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InheritedMethod not implemented")
}
func (UnimplementedInheritAndOverrideTwoServer) OverriddenMethod(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OverriddenMethod not implemented")
}
func (UnimplementedInheritAndOverrideTwoServer) mustEmbedUnimplementedInheritAndOverrideTwoServer() {}

// UnsafeInheritAndOverrideTwoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InheritAndOverrideTwoServer will
// result in compilation errors.
type UnsafeInheritAndOverrideTwoServer interface {
	mustEmbedUnimplementedInheritAndOverrideTwoServer()
}

func RegisterInheritAndOverrideTwoServer(s grpc.ServiceRegistrar, srv InheritAndOverrideTwoServer) {
	s.RegisterService(&InheritAndOverrideTwo_ServiceDesc, srv)
}

func _InheritAndOverrideTwo_InheritedMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InheritAndOverrideTwoServer).InheritedMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.corner_cases.InheritAndOverrideTwo/InheritedMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InheritAndOverrideTwoServer).InheritedMethod(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InheritAndOverrideTwo_OverriddenMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InheritAndOverrideTwoServer).OverriddenMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.corner_cases.InheritAndOverrideTwo/OverriddenMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InheritAndOverrideTwoServer).OverriddenMethod(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// InheritAndOverrideTwo_ServiceDesc is the grpc.ServiceDesc for InheritAndOverrideTwo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InheritAndOverrideTwo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.corner_cases.InheritAndOverrideTwo",
	HandlerType: (*InheritAndOverrideTwoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InheritedMethod",
			Handler:    _InheritAndOverrideTwo_InheritedMethod_Handler,
		},
		{
			MethodName: "OverriddenMethod",
			Handler:    _InheritAndOverrideTwo_OverriddenMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/api/corner_cases/inherit_and_override.proto",
}
