// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/corner_cases/inherit_and_override.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
)

var rbacService_InheritAndOverrideOne = rbac.Service{
	Name: "InheritAndOverrideOne",
	Methods: map[string]*rbac.Method{
		"OverriddenMethod": {
			Rules: &rbac.Rules{
				AllowPublic: rbac.Ptr(true),
			},
		},
	},
}

func (UnimplementedInheritAndOverrideOneServer) GetRBACService() *rbac.Service {
	return &rbacService_InheritAndOverrideOne
}

var rbacService_InheritAndOverrideTwo = rbac.Service{
	Name: "InheritAndOverrideTwo",
	Rules: &rbac.Rules{
		AllowPublic: rbac.Ptr(true),
	},
	Methods: map[string]*rbac.Method{
		"OverriddenMethod": {
			Rules: &rbac.Rules{
				AllowPublic: rbac.Ptr(false),
			},
		},
	},
}

func (UnimplementedInheritAndOverrideTwoServer) GetRBACService() *rbac.Service {
	return &rbacService_InheritAndOverrideTwo
}
