// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/corner_cases/mixed_types_access.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
)

var rbacService_MixedTypesAccess = rbac.Service{
	Name: "MixedTypesAccess",
	Rules: &rbac.Rules{
		RoleBased: &rbac.RoleBased{
			AllowedRoles: []string{
				"admin",
			},
		},
	},
	Methods: map[string]*rbac.Method{
		"OverrideWithAuthentication": {
			Rules: &rbac.Rules{
				RequireAuthn: rbac.Ptr(true),
			},
		},
		"OverrideWithPolicies": {
			Rules: &rbac.Rules{
				PolicyBased: &rbac.PolicyBased{
					PolicyNames: []string{
						"positive-policy-1",
					},
					Requirement: rbac.Requirement(1),
				},
			},
		},
		"OverrideWithRoles": {
			Rules: &rbac.Rules{
				RoleBased: &rbac.RoleBased{
					AllowedRoles: []string{
						"admin",
					},
				},
			},
		},
	},
}

func (UnimplementedMixedTypesAccessServer) GetRBACService() *rbac.Service {
	return &rbacService_MixedTypesAccess
}
