// Code generated by protoc-gen-go-guard. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/corner_cases/mixed_types_access.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-guard/pkg/guard"
)

var guardService_MixedTypesAccess = guard.Service{
	Name: "MixedTypesAccess",
	Rules: &guard.Rules{
		RoleBased: &guard.RoleBased{
			AllowedRoles: []string{
				"admin",
			},
		},
	},
	Methods: map[string]*guard.Method{
		"OverrideWithAuthentication": {
			Rules: &guard.Rules{
				RequireAuthn: guard.Ptr(true),
			},
		},
		"OverrideWithPolicies": {
			Rules: &guard.Rules{
				PolicyBased: &guard.PolicyBased{
					PolicyNames: []string{
						"positive-policy-1",
					},
					Requirement: guard.Requirement(1),
				},
			},
		},
		"OverrideWithRoles": {
			Rules: &guard.Rules{
				RoleBased: &guard.RoleBased{
					AllowedRoles: []string{
						"admin",
					},
				},
			},
		},
	},
}

func (UnimplementedMixedTypesAccessServer) GetGuardService() *guard.Service {
	return &guardService_MixedTypesAccess
}
