// Code generated by protoc-gen-go-guard. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/corner_cases/policy_based_access.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-guard/pkg/guard"
)

var guardService_PolicyBasedAccess = guard.Service{
	Name: "PolicyBasedAccess",
	Methods: map[string]*guard.Method{
		"EmptyPoliciesWithAllRequirement": {
			Rules: &guard.Rules{
				PolicyBased: &guard.PolicyBased{},
			},
		},
		"EmptyPoliciesWithAnyRequirement": {
			Rules: &guard.Rules{
				PolicyBased: &guard.PolicyBased{},
			},
		},
		"MultiplePoliciesWithAllRequirement": {
			Rules: &guard.Rules{
				PolicyBased: &guard.PolicyBased{
					PolicyNames: []string{
						"policy1",
						"policy2",
					},
					Requirement: guard.Requirement(1),
				},
			},
		},
		"MultiplePoliciesWithAnyRequirement": {
			Rules: &guard.Rules{
				PolicyBased: &guard.PolicyBased{
					PolicyNames: []string{
						"policy1",
						"policy2",
					},
				},
			},
		},
	},
}

func (UnimplementedPolicyBasedAccessServer) GetGuardService() *guard.Service {
	return &guardService_PolicyBasedAccess
}
