// Code generated by protoc-gen-go-guard. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/corner_cases/policy_based_access.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-guard/pkg/guard"
)

var guardService_PolicyBasedAccess = guard.Service{
	Name: "PolicyBasedAccess",
	Methods: map[string]*guard.Method{
		"EmptyPoliciesWithAllRequirement": {
			Rules: []*guard.Rule{
				{
					AuthenticatedAccess: &guard.AuthenticatedAccess{
						PolicyBased: &guard.PolicyBased{
							Policies: []string{},
							Match:    guard.Match(1),
						},
					},
				},
			},
		},
		"EmptyPoliciesWithAnyRequirement": {
			Rules: []*guard.Rule{
				{
					AuthenticatedAccess: &guard.AuthenticatedAccess{
						PolicyBased: &guard.PolicyBased{
							Policies: []string{},
							Match:    guard.Match(0),
						},
					},
				},
			},
		},
		"MultiplePoliciesWithAllRequirement": {
			Rules: []*guard.Rule{
				{
					AuthenticatedAccess: &guard.AuthenticatedAccess{
						PolicyBased: &guard.PolicyBased{
							Policies: []string{"policy1", "policy2"},
							Match:    guard.Match(1),
						},
					},
				},
			},
		},
		"MultiplePoliciesWithAnyRequirement": {
			Rules: []*guard.Rule{
				{
					AuthenticatedAccess: &guard.AuthenticatedAccess{
						PolicyBased: &guard.PolicyBased{
							Policies: []string{"policy1", "policy2"},
							Match:    guard.Match(0),
						},
					},
				},
			},
		},
	},
}

func (UnimplementedPolicyBasedAccessServer) GuardService() *guard.Service {
	return &guardService_PolicyBasedAccess
}
