// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/corner_cases/policy_based_access.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
)

var rbacService_PolicyBasedAccess = rbac.Service{
	Name: "PolicyBasedAccess",
	Methods: map[string]*rbac.Method{
		"EmptyPoliciesWithAllRequirement": {
			Rules: &rbac.Rules{
				PolicyBased: &rbac.PolicyBased{},
			},
		},
		"EmptyPoliciesWithAnyRequirement": {
			Rules: &rbac.Rules{
				PolicyBased: &rbac.PolicyBased{},
			},
		},
		"MultiplePoliciesWithAllRequirement": {
			Rules: &rbac.Rules{
				PolicyBased: &rbac.PolicyBased{
					PolicyNames: []string{
						"policy1",
						"policy2",
					},
					Requirement: rbac.Requirement(1),
				},
			},
		},
		"MultiplePoliciesWithAnyRequirement": {
			Rules: &rbac.Rules{
				PolicyBased: &rbac.PolicyBased{
					PolicyNames: []string{
						"policy1",
						"policy2",
					},
				},
			},
		},
	},
}

func (UnimplementedPolicyBasedAccessServer) GetRBACService() *rbac.Service {
	return &rbacService_PolicyBasedAccess
}
