// Code generated by protoc-gen-go-guard. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/corner_cases/role_based_access.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-guard/pkg/guard"
)

var guardService_RoleBasedAccess = guard.Service{
	Name: "RoleBasedAccess",
	Methods: map[string]*guard.Method{
		"EmptyRolesWithAllRequirement": {
			Rules: &guard.Rules{
				RoleBased: &guard.RoleBased{},
			},
		},
		"EmptyRolesWithAnyRequirement": {
			Rules: &guard.Rules{
				RoleBased: &guard.RoleBased{},
			},
		},
		"MultipleRolesWithAllRequirement": {
			Rules: &guard.Rules{
				RoleBased: &guard.RoleBased{
					AllowedRoles: []string{
						"admin",
						"manager",
					},
					Requirement: guard.Requirement(1),
				},
			},
		},
		"MultipleRolesWithAnyRequirement": {
			Rules: &guard.Rules{
				RoleBased: &guard.RoleBased{
					AllowedRoles: []string{
						"admin",
						"manager",
					},
				},
			},
		},
	},
}

func (UnimplementedRoleBasedAccessServer) GetGuardService() *guard.Service {
	return &guardService_RoleBasedAccess
}
