// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/corner_cases/role_based_access.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
)

var rbacService_RoleBasedAccess = rbac.Service{
	Name: "RoleBasedAccess",
	Methods: map[string]*rbac.Method{
		"EmptyRolesWithAllRequirement": {
			Rules: &rbac.Rules{
				RoleBased: &rbac.RoleBased{},
			},
		},
		"EmptyRolesWithAnyRequirement": {
			Rules: &rbac.Rules{
				RoleBased: &rbac.RoleBased{},
			},
		},
		"MultipleRolesWithAllRequirement": {
			Rules: &rbac.Rules{
				RoleBased: &rbac.RoleBased{
					AllowedRoles: []string{
						"admin",
						"manager",
					},
					Requirement: rbac.Requirement(1),
				},
			},
		},
		"MultipleRolesWithAnyRequirement": {
			Rules: &rbac.Rules{
				RoleBased: &rbac.RoleBased{
					AllowedRoles: []string{
						"admin",
						"manager",
					},
				},
			},
		},
	},
}

func (UnimplementedRoleBasedAccessServer) GetRBACService() *rbac.Service {
	return &rbacService_RoleBasedAccess
}
