// Code generated by protoc-gen-go-guard. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/demo/auth.proto

package demo

import (
	"github.com/casnerano/protoc-gen-go-guard/pkg/guard"
)

var guardService_Auth = guard.Service{
	Name: "Auth",
	Rules: []*guard.Rule{
		{
			AllowPublic: guard.Ptr(true),
		},
	},
	Methods: map[string]*guard.Method{
		"Logout": {
			Rules: []*guard.Rule{
				{
					RequireAuthentication: guard.Ptr(true),
				},
			},
		},
	},
}

func (UnimplementedAuthServer) GuardService() *guard.Service {
	return &guardService_Auth
}
