// Code generated by protoc-gen-go-guard. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/demo/auth.proto

package demo

import (
	"github.com/casnerano/protoc-gen-go-guard/pkg/guard"
)

var guardService_Auth = guard.Service{
	Name:  "Auth",
	Rules: &guard.Rules{},
	Methods: map[string]*guard.Method{
		"Logout": {
			Rules: &guard.Rules{
				RequireAuthn: guard.Ptr(true),
			},
		},
	},
}

func (UnimplementedAuthServer) GetGuardService() *guard.Service {
	return &guardService_Auth
}
