// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/demo/auth.proto

package demo

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
)

var rbacService_Auth = rbac.Service{
	Name:  "Auth",
	Rules: &rbac.Rules{},
	Methods: map[string]*rbac.Method{
		"Logout": {
			Rules: &rbac.Rules{
				RequireAuthn: rbac.Ptr(true),
			},
		},
	},
}

func (UnimplementedAuthServer) GetRBACService() *rbac.Service {
	return &rbacService_Auth
}
