// Code generated by protoc-gen-go-guard. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             v1374391166712.1374391166716.1374391166736
// source: example/api/demo/user.proto

package demo

import (
	"github.com/casnerano/protoc-gen-go-guard/pkg/guard"
)

var guardService_User = guard.Service{
	Name: "User",
	Rules: []*guard.Rule{
		{
			RequireAuthentication: guard.Ptr(true),
		},
	},
	Methods: map[string]*guard.Method{
		"DeleteProfile": {
			Rules: []*guard.Rule{
				{
					AuthenticatedAccess: &guard.AuthenticatedAccess{
						RoleBased: &guard.RoleBased{
							Roles: []string{"user", "verified"},
							Match: guard.Match(1),
						},
					},
				},
			},
		},
		"GetPublicProfile": {
			Rules: []*guard.Rule{
				{
					AllowPublic: guard.Ptr(true),
				},
			},
		},
		"UpdateProfileStatus": {
			Rules: []*guard.Rule{
				{
					AuthenticatedAccess: &guard.AuthenticatedAccess{
						PolicyBased: &guard.PolicyBased{
							Policies: []string{"demo-period", "premium"},
							Match:    guard.Match(0),
						},
					},
				},
			},
		},
	},
}

func (UnimplementedUserServer) GuardService() *guard.Service {
	return &guardService_User
}
