// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/demo/user.proto

package demo

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
)

var rbacService_User = rbac.Service{
	Name: "User",
	Rules: &rbac.Rules{
		RequireAuthn: rbac.Ptr(true),
	},
	Methods: map[string]*rbac.Method{
		"DeleteProfile": {
			Rules: &rbac.Rules{
				RoleBased: &rbac.RoleBased{
					AllowedRoles: []string{
						"user",
						"verified",
					},
					Requirement: rbac.Requirement(1),
				},
			},
		},
		"GetPublicProfile": {
			Rules: &rbac.Rules{
				AllowPublic: rbac.Ptr(true),
			},
		},
		"UpdateProfileStatus": {
			Rules: &rbac.Rules{
				PolicyBased: &rbac.PolicyBased{
					PolicyNames: []string{
						"demo-period",
						"premium",
					},
				},
			},
		},
	},
}

func (UnimplementedUserServer) GetRBACService() *rbac.Service {
	return &rbacService_User
}
