// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: proto/guard.proto

package guard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Match int32

const (
	Match_AT_LEAST_ONE Match = 0
	Match_ALL          Match = 1
)

// Enum value maps for Match.
var (
	Match_name = map[int32]string{
		0: "AT_LEAST_ONE",
		1: "ALL",
	}
	Match_value = map[string]int32{
		"AT_LEAST_ONE": 0,
		"ALL":          1,
	}
)

func (x Match) Enum() *Match {
	p := new(Match)
	*p = x
	return p
}

func (x Match) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Match) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guard_proto_enumTypes[0].Descriptor()
}

func (Match) Type() protoreflect.EnumType {
	return &file_proto_guard_proto_enumTypes[0]
}

func (x Match) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Match.Descriptor instead.
func (Match) EnumDescriptor() ([]byte, []int) {
	return file_proto_guard_proto_rawDescGZIP(), []int{0}
}

type RoleBased struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []string `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Match *Match   `protobuf:"varint,2,opt,name=match,proto3,enum=guard.Match,oneof" json:"match,omitempty"`
}

func (x *RoleBased) Reset() {
	*x = RoleBased{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleBased) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBased) ProtoMessage() {}

func (x *RoleBased) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBased.ProtoReflect.Descriptor instead.
func (*RoleBased) Descriptor() ([]byte, []int) {
	return file_proto_guard_proto_rawDescGZIP(), []int{0}
}

func (x *RoleBased) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RoleBased) GetMatch() Match {
	if x != nil && x.Match != nil {
		return *x.Match
	}
	return Match_AT_LEAST_ONE
}

type PolicyBased struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Policies []string `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	Match    *Match   `protobuf:"varint,2,opt,name=match,proto3,enum=guard.Match,oneof" json:"match,omitempty"`
}

func (x *PolicyBased) Reset() {
	*x = PolicyBased{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyBased) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBased) ProtoMessage() {}

func (x *PolicyBased) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBased.ProtoReflect.Descriptor instead.
func (*PolicyBased) Descriptor() ([]byte, []int) {
	return file_proto_guard_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyBased) GetPolicies() []string {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *PolicyBased) GetMatch() Match {
	if x != nil && x.Match != nil {
		return *x.Match
	}
	return Match_AT_LEAST_ONE
}

type Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Mode:
	//
	//	*Rule_AllowPublic
	//	*Rule_RequireAuthentication
	//	*Rule_AuthenticatedAccess
	Mode isRule_Mode `protobuf_oneof:"mode"`
}

func (x *Rule) Reset() {
	*x = Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_proto_guard_proto_rawDescGZIP(), []int{2}
}

func (m *Rule) GetMode() isRule_Mode {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (x *Rule) GetAllowPublic() bool {
	if x, ok := x.GetMode().(*Rule_AllowPublic); ok {
		return x.AllowPublic
	}
	return false
}

func (x *Rule) GetRequireAuthentication() bool {
	if x, ok := x.GetMode().(*Rule_RequireAuthentication); ok {
		return x.RequireAuthentication
	}
	return false
}

func (x *Rule) GetAuthenticatedAccess() *AuthenticatedAccess {
	if x, ok := x.GetMode().(*Rule_AuthenticatedAccess); ok {
		return x.AuthenticatedAccess
	}
	return nil
}

type isRule_Mode interface {
	isRule_Mode()
}

type Rule_AllowPublic struct {
	AllowPublic bool `protobuf:"varint,1,opt,name=allow_public,json=allowPublic,proto3,oneof"`
}

type Rule_RequireAuthentication struct {
	RequireAuthentication bool `protobuf:"varint,2,opt,name=require_authentication,json=requireAuthentication,proto3,oneof"`
}

type Rule_AuthenticatedAccess struct {
	AuthenticatedAccess *AuthenticatedAccess `protobuf:"bytes,3,opt,name=authenticated_access,json=authenticatedAccess,proto3,oneof"`
}

func (*Rule_AllowPublic) isRule_Mode() {}

func (*Rule_RequireAuthentication) isRule_Mode() {}

func (*Rule_AuthenticatedAccess) isRule_Mode() {}

type AuthenticatedAccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleBased   *RoleBased   `protobuf:"bytes,1,opt,name=role_based,json=roleBased,proto3" json:"role_based,omitempty"`
	PolicyBased *PolicyBased `protobuf:"bytes,2,opt,name=policy_based,json=policyBased,proto3" json:"policy_based,omitempty"`
}

func (x *AuthenticatedAccess) Reset() {
	*x = AuthenticatedAccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticatedAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatedAccess) ProtoMessage() {}

func (x *AuthenticatedAccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatedAccess.ProtoReflect.Descriptor instead.
func (*AuthenticatedAccess) Descriptor() ([]byte, []int) {
	return file_proto_guard_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticatedAccess) GetRoleBased() *RoleBased {
	if x != nil {
		return x.RoleBased
	}
	return nil
}

func (x *AuthenticatedAccess) GetPolicyBased() *PolicyBased {
	if x != nil {
		return x.PolicyBased
	}
	return nil
}

var file_proto_guard_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: ([]*Rule)(nil),
		Field:         50001,
		Name:          "guard.service_rules",
		Tag:           "bytes,50001,rep,name=service_rules",
		Filename:      "proto/guard.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: ([]*Rule)(nil),
		Field:         50002,
		Name:          "guard.method_rules",
		Tag:           "bytes,50002,rep,name=method_rules",
		Filename:      "proto/guard.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// repeated guard.Rule service_rules = 50001;
	E_ServiceRules = &file_proto_guard_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// repeated guard.Rule method_rules = 50002;
	E_MethodRules = &file_proto_guard_proto_extTypes[1]
)

var File_proto_guard_proto protoreflect.FileDescriptor

var file_proto_guard_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x75, 0x61, 0x72, 0x64, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x09,
	0x52, 0x6f, 0x6c, 0x65, 0x42, 0x61, 0x73, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12,
	0x27, 0x0a, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c,
	0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x48, 0x00, 0x52, 0x05,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x22, 0x5c, 0x0a, 0x0b, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x42, 0x61, 0x73, 0x65,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x12, 0x27, 0x0a,
	0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x67,
	0x75, 0x61, 0x72, 0x64, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x48, 0x00, 0x52, 0x05, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x22, 0xbd, 0x01, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x37,
	0x0a, 0x16, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00,
	0x52, 0x15, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4f, 0x0a, 0x14, 0x61, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x48, 0x00, 0x52, 0x13, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x22, 0x7d, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2f, 0x0a, 0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x5f,
	0x62, 0x61, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x75,
	0x61, 0x72, 0x64, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x61, 0x73, 0x65, 0x64, 0x52, 0x09, 0x72,
	0x6f, 0x6c, 0x65, 0x42, 0x61, 0x73, 0x65, 0x64, 0x12, 0x35, 0x0a, 0x0c, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x42, 0x61, 0x73,
	0x65, 0x64, 0x52, 0x0b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x42, 0x61, 0x73, 0x65, 0x64, 0x2a,
	0x22, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x54, 0x5f, 0x4c,
	0x45, 0x41, 0x53, 0x54, 0x5f, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c,
	0x4c, 0x10, 0x01, 0x3a, 0x53, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x3a, 0x50, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd2, 0x86, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0b, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x73, 0x6e, 0x65, 0x72, 0x61,
	0x6e, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f,
	0x2d, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x67, 0x75, 0x61,
	0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_guard_proto_rawDescOnce sync.Once
	file_proto_guard_proto_rawDescData = file_proto_guard_proto_rawDesc
)

func file_proto_guard_proto_rawDescGZIP() []byte {
	file_proto_guard_proto_rawDescOnce.Do(func() {
		file_proto_guard_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_guard_proto_rawDescData)
	})
	return file_proto_guard_proto_rawDescData
}

var file_proto_guard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_guard_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_guard_proto_goTypes = []interface{}{
	(Match)(0),                          // 0: guard.Match
	(*RoleBased)(nil),                   // 1: guard.RoleBased
	(*PolicyBased)(nil),                 // 2: guard.PolicyBased
	(*Rule)(nil),                        // 3: guard.Rule
	(*AuthenticatedAccess)(nil),         // 4: guard.AuthenticatedAccess
	(*descriptorpb.ServiceOptions)(nil), // 5: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 6: google.protobuf.MethodOptions
}
var file_proto_guard_proto_depIdxs = []int32{
	0, // 0: guard.RoleBased.match:type_name -> guard.Match
	0, // 1: guard.PolicyBased.match:type_name -> guard.Match
	4, // 2: guard.Rule.authenticated_access:type_name -> guard.AuthenticatedAccess
	1, // 3: guard.AuthenticatedAccess.role_based:type_name -> guard.RoleBased
	2, // 4: guard.AuthenticatedAccess.policy_based:type_name -> guard.PolicyBased
	5, // 5: guard.service_rules:extendee -> google.protobuf.ServiceOptions
	6, // 6: guard.method_rules:extendee -> google.protobuf.MethodOptions
	3, // 7: guard.service_rules:type_name -> guard.Rule
	3, // 8: guard.method_rules:type_name -> guard.Rule
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	7, // [7:9] is the sub-list for extension type_name
	5, // [5:7] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_guard_proto_init() }
func file_proto_guard_proto_init() {
	if File_proto_guard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_guard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleBased); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyBased); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticatedAccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_guard_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_guard_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_proto_guard_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Rule_AllowPublic)(nil),
		(*Rule_RequireAuthentication)(nil),
		(*Rule_AuthenticatedAccess)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_guard_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_proto_guard_proto_goTypes,
		DependencyIndexes: file_proto_guard_proto_depIdxs,
		EnumInfos:         file_proto_guard_proto_enumTypes,
		MessageInfos:      file_proto_guard_proto_msgTypes,
		ExtensionInfos:    file_proto_guard_proto_extTypes,
	}.Build()
	File_proto_guard_proto = out.File
	file_proto_guard_proto_rawDesc = nil
	file_proto_guard_proto_goTypes = nil
	file_proto_guard_proto_depIdxs = nil
}
