// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: proto/guard.proto

package guard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Requirement int32

const (
	Requirement_ANY Requirement = 0
	Requirement_ALL Requirement = 1
)

// Enum value maps for Requirement.
var (
	Requirement_name = map[int32]string{
		0: "ANY",
		1: "ALL",
	}
	Requirement_value = map[string]int32{
		"ANY": 0,
		"ALL": 1,
	}
)

func (x Requirement) Enum() *Requirement {
	p := new(Requirement)
	*p = x
	return p
}

func (x Requirement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Requirement) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guard_proto_enumTypes[0].Descriptor()
}

func (Requirement) Type() protoreflect.EnumType {
	return &file_proto_guard_proto_enumTypes[0]
}

func (x Requirement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Requirement.Descriptor instead.
func (Requirement) EnumDescriptor() ([]byte, []int) {
	return file_proto_guard_proto_rawDescGZIP(), []int{0}
}

type RoleBased struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllowedRoles []string     `protobuf:"bytes,1,rep,name=allowed_roles,json=allowedRoles,proto3" json:"allowed_roles,omitempty"`
	Requirement  *Requirement `protobuf:"varint,2,opt,name=requirement,proto3,enum=guard.Requirement,oneof" json:"requirement,omitempty"`
}

func (x *RoleBased) Reset() {
	*x = RoleBased{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleBased) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBased) ProtoMessage() {}

func (x *RoleBased) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBased.ProtoReflect.Descriptor instead.
func (*RoleBased) Descriptor() ([]byte, []int) {
	return file_proto_guard_proto_rawDescGZIP(), []int{0}
}

func (x *RoleBased) GetAllowedRoles() []string {
	if x != nil {
		return x.AllowedRoles
	}
	return nil
}

func (x *RoleBased) GetRequirement() Requirement {
	if x != nil && x.Requirement != nil {
		return *x.Requirement
	}
	return Requirement_ANY
}

type PolicyBased struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyNames []string     `protobuf:"bytes,1,rep,name=policy_names,json=policyNames,proto3" json:"policy_names,omitempty"`
	Requirement *Requirement `protobuf:"varint,2,opt,name=requirement,proto3,enum=guard.Requirement,oneof" json:"requirement,omitempty"`
}

func (x *PolicyBased) Reset() {
	*x = PolicyBased{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyBased) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBased) ProtoMessage() {}

func (x *PolicyBased) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBased.ProtoReflect.Descriptor instead.
func (*PolicyBased) Descriptor() ([]byte, []int) {
	return file_proto_guard_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyBased) GetPolicyNames() []string {
	if x != nil {
		return x.PolicyNames
	}
	return nil
}

func (x *PolicyBased) GetRequirement() Requirement {
	if x != nil && x.Requirement != nil {
		return *x.Requirement
	}
	return Requirement_ANY
}

type Rules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to OneOf:
	//
	//	*Rules_AllowPublic
	//	*Rules_RequireAuthentication
	//	*Rules_RoleBased
	//	*Rules_PolicyBased
	OneOf isRules_OneOf `protobuf_oneof:"OneOf"`
}

func (x *Rules) Reset() {
	*x = Rules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rules) ProtoMessage() {}

func (x *Rules) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rules.ProtoReflect.Descriptor instead.
func (*Rules) Descriptor() ([]byte, []int) {
	return file_proto_guard_proto_rawDescGZIP(), []int{2}
}

func (m *Rules) GetOneOf() isRules_OneOf {
	if m != nil {
		return m.OneOf
	}
	return nil
}

func (x *Rules) GetAllowPublic() bool {
	if x, ok := x.GetOneOf().(*Rules_AllowPublic); ok {
		return x.AllowPublic
	}
	return false
}

func (x *Rules) GetRequireAuthentication() bool {
	if x, ok := x.GetOneOf().(*Rules_RequireAuthentication); ok {
		return x.RequireAuthentication
	}
	return false
}

func (x *Rules) GetRoleBased() *RoleBased {
	if x, ok := x.GetOneOf().(*Rules_RoleBased); ok {
		return x.RoleBased
	}
	return nil
}

func (x *Rules) GetPolicyBased() *PolicyBased {
	if x, ok := x.GetOneOf().(*Rules_PolicyBased); ok {
		return x.PolicyBased
	}
	return nil
}

type isRules_OneOf interface {
	isRules_OneOf()
}

type Rules_AllowPublic struct {
	AllowPublic bool `protobuf:"varint,1,opt,name=allow_public,json=allowPublic,proto3,oneof"`
}

type Rules_RequireAuthentication struct {
	RequireAuthentication bool `protobuf:"varint,2,opt,name=require_authentication,json=requireAuthentication,proto3,oneof"`
}

type Rules_RoleBased struct {
	RoleBased *RoleBased `protobuf:"bytes,3,opt,name=role_based,json=roleBased,proto3,oneof"`
}

type Rules_PolicyBased struct {
	PolicyBased *PolicyBased `protobuf:"bytes,4,opt,name=policy_based,json=policyBased,proto3,oneof"`
}

func (*Rules_AllowPublic) isRules_OneOf() {}

func (*Rules_RequireAuthentication) isRules_OneOf() {}

func (*Rules_RoleBased) isRules_OneOf() {}

func (*Rules_PolicyBased) isRules_OneOf() {}

var file_proto_guard_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Rules)(nil),
		Field:         50001,
		Name:          "guard.service_rules",
		Tag:           "bytes,50001,opt,name=service_rules",
		Filename:      "proto/guard.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Rules)(nil),
		Field:         50002,
		Name:          "guard.method_rules",
		Tag:           "bytes,50002,opt,name=method_rules",
		Filename:      "proto/guard.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional guard.Rules service_rules = 50001;
	E_ServiceRules = &file_proto_guard_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional guard.Rules method_rules = 50002;
	E_MethodRules = &file_proto_guard_proto_extTypes[1]
)

var File_proto_guard_proto protoreflect.FileDescriptor

var file_proto_guard_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x75, 0x61, 0x72, 0x64, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x09,
	0x52, 0x6f, 0x6c, 0x65, 0x42, 0x61, 0x73, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x39,
	0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x7b, 0x0a, 0x0b, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x42, 0x61, 0x73, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x0b, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xda, 0x01, 0x0a, 0x05, 0x52, 0x75, 0x6c, 0x65, 0x73,
	0x12, 0x23, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x37, 0x0a, 0x16, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x5f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x15, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31,
	0x0a, 0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42,
	0x61, 0x73, 0x65, 0x64, 0x48, 0x00, 0x52, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x42, 0x61, 0x73, 0x65,
	0x64, 0x12, 0x37, 0x0a, 0x0c, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x62, 0x61, 0x73, 0x65,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x42, 0x61, 0x73, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x42, 0x61, 0x73, 0x65, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x4f, 0x6e,
	0x65, 0x4f, 0x66, 0x2a, 0x1f, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4e, 0x59, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x4c, 0x4c, 0x10, 0x01, 0x3a, 0x54, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x0c, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x3a, 0x51, 0x0a, 0x0c, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd2, 0x86, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x73,
	0x52, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x42, 0x36, 0x5a,
	0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x73, 0x6e,
	0x65, 0x72, 0x61, 0x6e, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e,
	0x2d, 0x67, 0x6f, 0x2d, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x67, 0x75, 0x61, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_guard_proto_rawDescOnce sync.Once
	file_proto_guard_proto_rawDescData = file_proto_guard_proto_rawDesc
)

func file_proto_guard_proto_rawDescGZIP() []byte {
	file_proto_guard_proto_rawDescOnce.Do(func() {
		file_proto_guard_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_guard_proto_rawDescData)
	})
	return file_proto_guard_proto_rawDescData
}

var file_proto_guard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_guard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_guard_proto_goTypes = []interface{}{
	(Requirement)(0),                    // 0: guard.Requirement
	(*RoleBased)(nil),                   // 1: guard.RoleBased
	(*PolicyBased)(nil),                 // 2: guard.PolicyBased
	(*Rules)(nil),                       // 3: guard.Rules
	(*descriptorpb.ServiceOptions)(nil), // 4: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 5: google.protobuf.MethodOptions
}
var file_proto_guard_proto_depIdxs = []int32{
	0, // 0: guard.RoleBased.requirement:type_name -> guard.Requirement
	0, // 1: guard.PolicyBased.requirement:type_name -> guard.Requirement
	1, // 2: guard.Rules.role_based:type_name -> guard.RoleBased
	2, // 3: guard.Rules.policy_based:type_name -> guard.PolicyBased
	4, // 4: guard.service_rules:extendee -> google.protobuf.ServiceOptions
	5, // 5: guard.method_rules:extendee -> google.protobuf.MethodOptions
	3, // 6: guard.service_rules:type_name -> guard.Rules
	3, // 7: guard.method_rules:type_name -> guard.Rules
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	6, // [6:8] is the sub-list for extension type_name
	4, // [4:6] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_guard_proto_init() }
func file_proto_guard_proto_init() {
	if File_proto_guard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_guard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleBased); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyBased); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_guard_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_guard_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_proto_guard_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Rules_AllowPublic)(nil),
		(*Rules_RequireAuthentication)(nil),
		(*Rules_RoleBased)(nil),
		(*Rules_PolicyBased)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_guard_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_proto_guard_proto_goTypes,
		DependencyIndexes: file_proto_guard_proto_depIdxs,
		EnumInfos:         file_proto_guard_proto_enumTypes,
		MessageInfos:      file_proto_guard_proto_msgTypes,
		ExtensionInfos:    file_proto_guard_proto_extTypes,
	}.Build()
	File_proto_guard_proto = out.File
	file_proto_guard_proto_rawDesc = nil
	file_proto_guard_proto_goTypes = nil
	file_proto_guard_proto_depIdxs = nil
}
