// Code generated by protoc-gen-go-guard. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             v6.32.0
// source: e2e/grpc/api/corner_cases/default_and_empty.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-guard/pkg/guard"
)

var guardService_EmptyMethodRules = guard.Service{
	Name: "EmptyMethodRules",
	Methods: map[string]*guard.Method{
		"GetOne": {
			Rules: []*guard.Rule{},
		},
	},
}

func (UnimplementedEmptyMethodRulesServer) GuardService() *guard.Service {
	return &guardService_EmptyMethodRules
}

var guardService_EmptyServiceAndMethodRules = guard.Service{
	Name: "EmptyServiceAndMethodRules",
	Methods: map[string]*guard.Method{
		"GetOne": {
			Rules: []*guard.Rule{},
		},
	},
}

func (UnimplementedEmptyServiceAndMethodRulesServer) GuardService() *guard.Service {
	return &guardService_EmptyServiceAndMethodRules
}
