// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: e2e/grpc/api/corner_cases/mixed_types_access.proto

package corner_cases

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MixedTypesAccessClient is the client API for MixedTypesAccess service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MixedTypesAccessClient interface {
	// Call with override rules.
	OverrideWithPolicies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Call with override rules.
	OverrideWithRoles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Call with override rules.
	OverrideWithAuthentication(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type mixedTypesAccessClient struct {
	cc grpc.ClientConnInterface
}

func NewMixedTypesAccessClient(cc grpc.ClientConnInterface) MixedTypesAccessClient {
	return &mixedTypesAccessClient{cc}
}

func (c *mixedTypesAccessClient) OverrideWithPolicies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/e2e.corner_cases.MixedTypesAccess/OverrideWithPolicies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mixedTypesAccessClient) OverrideWithRoles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/e2e.corner_cases.MixedTypesAccess/OverrideWithRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mixedTypesAccessClient) OverrideWithAuthentication(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/e2e.corner_cases.MixedTypesAccess/OverrideWithAuthentication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MixedTypesAccessServer is the server API for MixedTypesAccess service.
// All implementations must embed UnimplementedMixedTypesAccessServer
// for forward compatibility
type MixedTypesAccessServer interface {
	// Call with override rules.
	OverrideWithPolicies(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Call with override rules.
	OverrideWithRoles(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Call with override rules.
	OverrideWithAuthentication(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedMixedTypesAccessServer()
}

// UnimplementedMixedTypesAccessServer must be embedded to have forward compatible implementations.
type UnimplementedMixedTypesAccessServer struct {
}

func (UnimplementedMixedTypesAccessServer) OverrideWithPolicies(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OverrideWithPolicies not implemented")
}
func (UnimplementedMixedTypesAccessServer) OverrideWithRoles(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OverrideWithRoles not implemented")
}
func (UnimplementedMixedTypesAccessServer) OverrideWithAuthentication(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OverrideWithAuthentication not implemented")
}
func (UnimplementedMixedTypesAccessServer) mustEmbedUnimplementedMixedTypesAccessServer() {}

// UnsafeMixedTypesAccessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MixedTypesAccessServer will
// result in compilation errors.
type UnsafeMixedTypesAccessServer interface {
	mustEmbedUnimplementedMixedTypesAccessServer()
}

func RegisterMixedTypesAccessServer(s grpc.ServiceRegistrar, srv MixedTypesAccessServer) {
	s.RegisterService(&MixedTypesAccess_ServiceDesc, srv)
}

func _MixedTypesAccess_OverrideWithPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MixedTypesAccessServer).OverrideWithPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/e2e.corner_cases.MixedTypesAccess/OverrideWithPolicies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MixedTypesAccessServer).OverrideWithPolicies(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MixedTypesAccess_OverrideWithRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MixedTypesAccessServer).OverrideWithRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/e2e.corner_cases.MixedTypesAccess/OverrideWithRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MixedTypesAccessServer).OverrideWithRoles(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MixedTypesAccess_OverrideWithAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MixedTypesAccessServer).OverrideWithAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/e2e.corner_cases.MixedTypesAccess/OverrideWithAuthentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MixedTypesAccessServer).OverrideWithAuthentication(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MixedTypesAccess_ServiceDesc is the grpc.ServiceDesc for MixedTypesAccess service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MixedTypesAccess_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "e2e.corner_cases.MixedTypesAccess",
	HandlerType: (*MixedTypesAccessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OverrideWithPolicies",
			Handler:    _MixedTypesAccess_OverrideWithPolicies_Handler,
		},
		{
			MethodName: "OverrideWithRoles",
			Handler:    _MixedTypesAccess_OverrideWithRoles_Handler,
		},
		{
			MethodName: "OverrideWithAuthentication",
			Handler:    _MixedTypesAccess_OverrideWithAuthentication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "e2e/grpc/api/corner_cases/mixed_types_access.proto",
}
