// Code generated by protoc-gen-go-guard. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             v1374391166712.1374391166716.1374391166736
// source: e2e/grpc/api/corner_cases/mixed_types_access.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-guard/pkg/guard"
)

var guardService_MixedTypesAccess = guard.Service{
	Name: "MixedTypesAccess",
	Rules: []*guard.Rule{
		{
			AuthenticatedAccess: &guard.AuthenticatedAccess{
				RoleBased: &guard.RoleBased{
					Roles: []string{"admin"},
					Match: guard.Match(0),
				},
			},
		},
	},
	Methods: map[string]*guard.Method{
		"OverrideWithAuthentication": {
			Rules: []*guard.Rule{
				{
					RequireAuthentication: guard.Ptr(true),
				},
			},
		},
		"OverrideWithPolicies": {
			Rules: []*guard.Rule{
				{
					AuthenticatedAccess: &guard.AuthenticatedAccess{
						PolicyBased: &guard.PolicyBased{
							Policies: []string{"positive-policy-1"},
							Match:    guard.Match(1),
						},
					},
				},
			},
		},
		"OverrideWithRoles": {
			Rules: []*guard.Rule{
				{
					AuthenticatedAccess: &guard.AuthenticatedAccess{
						RoleBased: &guard.RoleBased{
							Roles: []string{"admin"},
							Match: guard.Match(1),
						},
					},
				},
			},
		},
	},
}

func (UnimplementedMixedTypesAccessServer) GuardService() *guard.Service {
	return &guardService_MixedTypesAccess
}
