// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: e2e/grpc/api/corner_cases/policy_based_access.proto

package corner_cases

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PolicyBasedAccessClient is the client API for PolicyBasedAccess service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyBasedAccessClient interface {
	EmptyPoliciesWithAnyRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	EmptyPoliciesWithAllRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MultiplePoliciesWithAnyRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MultiplePoliciesWithAllRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type policyBasedAccessClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyBasedAccessClient(cc grpc.ClientConnInterface) PolicyBasedAccessClient {
	return &policyBasedAccessClient{cc}
}

func (c *policyBasedAccessClient) EmptyPoliciesWithAnyRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/e2e.corner_cases.PolicyBasedAccess/EmptyPoliciesWithAnyRequirement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyBasedAccessClient) EmptyPoliciesWithAllRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/e2e.corner_cases.PolicyBasedAccess/EmptyPoliciesWithAllRequirement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyBasedAccessClient) MultiplePoliciesWithAnyRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/e2e.corner_cases.PolicyBasedAccess/MultiplePoliciesWithAnyRequirement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyBasedAccessClient) MultiplePoliciesWithAllRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/e2e.corner_cases.PolicyBasedAccess/MultiplePoliciesWithAllRequirement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyBasedAccessServer is the server API for PolicyBasedAccess service.
// All implementations must embed UnimplementedPolicyBasedAccessServer
// for forward compatibility
type PolicyBasedAccessServer interface {
	EmptyPoliciesWithAnyRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	EmptyPoliciesWithAllRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	MultiplePoliciesWithAnyRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	MultiplePoliciesWithAllRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedPolicyBasedAccessServer()
}

// UnimplementedPolicyBasedAccessServer must be embedded to have forward compatible implementations.
type UnimplementedPolicyBasedAccessServer struct {
}

func (UnimplementedPolicyBasedAccessServer) EmptyPoliciesWithAnyRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmptyPoliciesWithAnyRequirement not implemented")
}
func (UnimplementedPolicyBasedAccessServer) EmptyPoliciesWithAllRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmptyPoliciesWithAllRequirement not implemented")
}
func (UnimplementedPolicyBasedAccessServer) MultiplePoliciesWithAnyRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiplePoliciesWithAnyRequirement not implemented")
}
func (UnimplementedPolicyBasedAccessServer) MultiplePoliciesWithAllRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiplePoliciesWithAllRequirement not implemented")
}
func (UnimplementedPolicyBasedAccessServer) mustEmbedUnimplementedPolicyBasedAccessServer() {}

// UnsafePolicyBasedAccessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyBasedAccessServer will
// result in compilation errors.
type UnsafePolicyBasedAccessServer interface {
	mustEmbedUnimplementedPolicyBasedAccessServer()
}

func RegisterPolicyBasedAccessServer(s grpc.ServiceRegistrar, srv PolicyBasedAccessServer) {
	s.RegisterService(&PolicyBasedAccess_ServiceDesc, srv)
}

func _PolicyBasedAccess_EmptyPoliciesWithAnyRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyBasedAccessServer).EmptyPoliciesWithAnyRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/e2e.corner_cases.PolicyBasedAccess/EmptyPoliciesWithAnyRequirement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyBasedAccessServer).EmptyPoliciesWithAnyRequirement(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyBasedAccess_EmptyPoliciesWithAllRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyBasedAccessServer).EmptyPoliciesWithAllRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/e2e.corner_cases.PolicyBasedAccess/EmptyPoliciesWithAllRequirement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyBasedAccessServer).EmptyPoliciesWithAllRequirement(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyBasedAccess_MultiplePoliciesWithAnyRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyBasedAccessServer).MultiplePoliciesWithAnyRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/e2e.corner_cases.PolicyBasedAccess/MultiplePoliciesWithAnyRequirement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyBasedAccessServer).MultiplePoliciesWithAnyRequirement(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyBasedAccess_MultiplePoliciesWithAllRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyBasedAccessServer).MultiplePoliciesWithAllRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/e2e.corner_cases.PolicyBasedAccess/MultiplePoliciesWithAllRequirement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyBasedAccessServer).MultiplePoliciesWithAllRequirement(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyBasedAccess_ServiceDesc is the grpc.ServiceDesc for PolicyBasedAccess service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyBasedAccess_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "e2e.corner_cases.PolicyBasedAccess",
	HandlerType: (*PolicyBasedAccessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmptyPoliciesWithAnyRequirement",
			Handler:    _PolicyBasedAccess_EmptyPoliciesWithAnyRequirement_Handler,
		},
		{
			MethodName: "EmptyPoliciesWithAllRequirement",
			Handler:    _PolicyBasedAccess_EmptyPoliciesWithAllRequirement_Handler,
		},
		{
			MethodName: "MultiplePoliciesWithAnyRequirement",
			Handler:    _PolicyBasedAccess_MultiplePoliciesWithAnyRequirement_Handler,
		},
		{
			MethodName: "MultiplePoliciesWithAllRequirement",
			Handler:    _PolicyBasedAccess_MultiplePoliciesWithAllRequirement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "e2e/grpc/api/corner_cases/policy_based_access.proto",
}
