// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.0
// source: e2e/grpc/api/corner_cases/role_based_access.proto

package corner_cases

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RoleBasedAccessClient is the client API for RoleBasedAccess service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoleBasedAccessClient interface {
	EmptyRolesWithAnyRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	EmptyRolesWithAllRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MultipleRolesWithAnyRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MultipleRolesWithAllRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type roleBasedAccessClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleBasedAccessClient(cc grpc.ClientConnInterface) RoleBasedAccessClient {
	return &roleBasedAccessClient{cc}
}

func (c *roleBasedAccessClient) EmptyRolesWithAnyRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/e2e.corner_cases.RoleBasedAccess/EmptyRolesWithAnyRequirement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleBasedAccessClient) EmptyRolesWithAllRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/e2e.corner_cases.RoleBasedAccess/EmptyRolesWithAllRequirement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleBasedAccessClient) MultipleRolesWithAnyRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/e2e.corner_cases.RoleBasedAccess/MultipleRolesWithAnyRequirement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleBasedAccessClient) MultipleRolesWithAllRequirement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/e2e.corner_cases.RoleBasedAccess/MultipleRolesWithAllRequirement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleBasedAccessServer is the server API for RoleBasedAccess service.
// All implementations must embed UnimplementedRoleBasedAccessServer
// for forward compatibility
type RoleBasedAccessServer interface {
	EmptyRolesWithAnyRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	EmptyRolesWithAllRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	MultipleRolesWithAnyRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	MultipleRolesWithAllRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedRoleBasedAccessServer()
}

// UnimplementedRoleBasedAccessServer must be embedded to have forward compatible implementations.
type UnimplementedRoleBasedAccessServer struct {
}

func (UnimplementedRoleBasedAccessServer) EmptyRolesWithAnyRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmptyRolesWithAnyRequirement not implemented")
}
func (UnimplementedRoleBasedAccessServer) EmptyRolesWithAllRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmptyRolesWithAllRequirement not implemented")
}
func (UnimplementedRoleBasedAccessServer) MultipleRolesWithAnyRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultipleRolesWithAnyRequirement not implemented")
}
func (UnimplementedRoleBasedAccessServer) MultipleRolesWithAllRequirement(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultipleRolesWithAllRequirement not implemented")
}
func (UnimplementedRoleBasedAccessServer) mustEmbedUnimplementedRoleBasedAccessServer() {}

// UnsafeRoleBasedAccessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleBasedAccessServer will
// result in compilation errors.
type UnsafeRoleBasedAccessServer interface {
	mustEmbedUnimplementedRoleBasedAccessServer()
}

func RegisterRoleBasedAccessServer(s grpc.ServiceRegistrar, srv RoleBasedAccessServer) {
	s.RegisterService(&RoleBasedAccess_ServiceDesc, srv)
}

func _RoleBasedAccess_EmptyRolesWithAnyRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleBasedAccessServer).EmptyRolesWithAnyRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/e2e.corner_cases.RoleBasedAccess/EmptyRolesWithAnyRequirement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleBasedAccessServer).EmptyRolesWithAnyRequirement(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleBasedAccess_EmptyRolesWithAllRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleBasedAccessServer).EmptyRolesWithAllRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/e2e.corner_cases.RoleBasedAccess/EmptyRolesWithAllRequirement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleBasedAccessServer).EmptyRolesWithAllRequirement(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleBasedAccess_MultipleRolesWithAnyRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleBasedAccessServer).MultipleRolesWithAnyRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/e2e.corner_cases.RoleBasedAccess/MultipleRolesWithAnyRequirement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleBasedAccessServer).MultipleRolesWithAnyRequirement(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleBasedAccess_MultipleRolesWithAllRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleBasedAccessServer).MultipleRolesWithAllRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/e2e.corner_cases.RoleBasedAccess/MultipleRolesWithAllRequirement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleBasedAccessServer).MultipleRolesWithAllRequirement(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RoleBasedAccess_ServiceDesc is the grpc.ServiceDesc for RoleBasedAccess service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoleBasedAccess_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "e2e.corner_cases.RoleBasedAccess",
	HandlerType: (*RoleBasedAccessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmptyRolesWithAnyRequirement",
			Handler:    _RoleBasedAccess_EmptyRolesWithAnyRequirement_Handler,
		},
		{
			MethodName: "EmptyRolesWithAllRequirement",
			Handler:    _RoleBasedAccess_EmptyRolesWithAllRequirement_Handler,
		},
		{
			MethodName: "MultipleRolesWithAnyRequirement",
			Handler:    _RoleBasedAccess_MultipleRolesWithAnyRequirement_Handler,
		},
		{
			MethodName: "MultipleRolesWithAllRequirement",
			Handler:    _RoleBasedAccess_MultipleRolesWithAllRequirement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "e2e/grpc/api/corner_cases/role_based_access.proto",
}
