// Code generated by protoc-gen-go-guard. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: e2e/grpc/api/corner_cases/role_based_access.proto

package corner_cases

import (
	"github.com/casnerano/protoc-gen-go-guard/pkg/guard"
)

var guardService_RoleBasedAccess = guard.Service{
	Name: "RoleBasedAccess",
	Methods: map[string]*guard.Method{
		"EmptyRolesWithAllRequirement": {
			Rules: []*guard.Rule{
				{
					AuthenticatedAccess: &guard.AuthenticatedAccess{
						RoleBased: &guard.RoleBased{
							Roles: []string{},
							Match: guard.Match(1),
						},
					},
				},
			},
		},
		"EmptyRolesWithAnyRequirement": {
			Rules: []*guard.Rule{
				{
					AuthenticatedAccess: &guard.AuthenticatedAccess{
						RoleBased: &guard.RoleBased{
							Roles: []string{},
							Match: guard.Match(0),
						},
					},
				},
			},
		},
		"MultipleRolesWithAllRequirement": {
			Rules: []*guard.Rule{
				{
					AuthenticatedAccess: &guard.AuthenticatedAccess{
						RoleBased: &guard.RoleBased{
							Roles: []string{"admin", "manager"},
							Match: guard.Match(1),
						},
					},
				},
			},
		},
		"MultipleRolesWithAnyRequirement": {
			Rules: []*guard.Rule{
				{
					AuthenticatedAccess: &guard.AuthenticatedAccess{
						RoleBased: &guard.RoleBased{
							Roles: []string{"admin", "manager"},
							Match: guard.Match(0),
						},
					},
				},
			},
		},
	},
}

func (UnimplementedRoleBasedAccessServer) GuardService() *guard.Service {
	return &guardService_RoleBasedAccess
}
